pipeline:
  build:
    image: segurosfalabella.azurecr.io/sf/node-dev:10-latest
    commands:
      - npm install
      
  docker_publish:
    image: plugins/docker
    registry: segurosfalabella.azurecr.io
    repo: segurosfalabella.azurecr.io/api-qr-rsa
    tags:
      - test
      - c-${DRONE_COMMIT_SHA}
      - b-${DRONE_BUILD_NUMBER}
    secrets: [ docker_username , docker_password ]

  deploy_staging:
    image: segurosfalabella.azurecr.io/drone/drone-deployer:b-85
    uri: https://api.staging.segurosfalabella.cloud/deployer/v2/deployments
    stack: api-qr-rsa
    filename: stack.yaml
    environment_vars:
      ENVIRONMENT: staging
      VERSION: b-${DRONE_BUILD_NUMBER}
    vault_kv: secret/project/api-qr-rsa/staging
    secrets: [vault_token]
    when:
      branch: master

  